### ISSUE TITLE
Problem with ISO-8859-1 Encoding?

### ISSUE THREAD

**Issue by Sharj** [monkeydom/TCMXMLWriter#1]
Hey, 
I'm setting UTF-8 in dictionaryWithObjectsAndKeys and I have characters like  Æ, ø and å  in my NSString when creating XML. When I see the created XML document in a text editor or browser it shows garbage values instead of special characters. Any quick tip on how to fix that?
Thanks.

**Comment by monkeydom** [comment]
probably setting the encoding of your source file correctly to UTF-8 in xcode? or you should use localizeable.strings files to bring in your unicode characters to your code.
